### ISSUE TITLE
Tracking: Migrate functions to SDK

### ISSUE THREAD

**Issue by martindekov** [openfaas/openfaas-cloud#609]
## Expected Behaviour

In [faas-cli PR #753](https://github.com/openfaas/faas-cli/pull/753) SDK in Go for the gateway was introduced. We should be moving to this one as opposed the having different logic to communicate with the OpenFaaS API in every function

## Current Behaviour

Every function has its own way to communicate with the OF API

## Possible Solution

Vendor the [Introduced SDK](https://github.com/openfaas/faas-cli/pull/753) in every function and use it as opposed to custom logic.

## Steps to Reproduce (for bugs)

1. Check every function has its own way of communicating with the API

## Context

Functions to be moved:
* [x] builshiprun @viveksyngh 
* [x] garbage collect @viveksyngh 
* [x] function-logs @martindekov 
* [x] list-functions @martindekov 

More to be added.

**Comment by alexellis** [comment]
What about the other OpenFaaS REST calls?

**Comment by martindekov** [comment]
Thats why I have put:
```
More to be added.
```
I will go through all functions and list them properly replacing this sentence with the rest functions.

**Comment by viveksyngh** [comment]
Other functions are,
```
function-logs
list-functions
```

**Comment by martindekov** [comment]
Added to the list :+1:

**Comment by viveksyngh** [comment]
I will take buildshiprun and add to the my existing PR.

**Comment by martindekov** [comment]
All four are merged.
